--------------------------------------------------------------------------------
-- obj_code_pkg.vhdl - Application object code in vhdl constant string format
-- Generated by hex_to_vhdl_v1_0.exe
-- © 2013 Antony Burrows. All Rights Reserved.
--------------------------------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.light52_pkg.all;

package obj_code_pkg is


-- Size of XCODE memory in bytes.
constant XCODE_SIZE : natural := 1024;
-- Size of XDATA memory in bytes.
constant XDATA_SIZE : natural := 0;

-- Object code initialization constant.
constant object_code : t_obj_code(0 to 29) := (
	X"00", X"00", X"74", X"FF", X"F5", X"80", X"11", X"12", 
	X"00", X"74", X"00", X"F5", X"80", X"11", X"12", X"00", 
	X"80", X"EE", X"11", X"15", X"22", X"7E", X"FA", X"7F", 
	X"FA", X"DE", X"FE", X"DF", X"FC", X"22"
);

end package obj_code_pkg;
